'use strict';

const fs = require('fs');
const assert = require('assert');

async function main() {
  const [wasmPath, ...expectations] = process.argv.slice(2);
  if (!wasmPath || expectations.length === 0) {
    throw new Error('usage: node scripts/verify_compiler_wasm.js <module.wasm> NAME=VALUE [...]');
  }

  const expected = new Map();
  for (const item of expectations) {
    const split = item.indexOf('=');
    if (split < 1) throw new Error(`invalid expectation: ${item}`);
    expected.set(item.slice(0, split), Number(item.slice(split + 1)));
  }

  const bytes = fs.readFileSync(wasmPath);
  assert.strictEqual(WebAssembly.validate(bytes), true, 'generated bytes are not a valid WebAssembly module');

  const { instance } = await WebAssembly.instantiate(bytes, {});
  assert.strictEqual(typeof instance.exports.i13_run, 'function', 'i13_run export missing');

  const verify = () => {
    for (const [name, value] of expected) {
      const global = instance.exports[`i13.global.${name}`];
      const state = instance.exports[`i13.state.${name}`];
      assert(global instanceof WebAssembly.Global, `missing numeric export i13.global.${name}`);
      assert(state instanceof WebAssembly.Global, `missing state export i13.state.${name}`);
      assert.strictEqual(state.value, 1, `${name} is not bound after execution`);
      assert.strictEqual(global.value, value, `${name} differs from reference VM`);
    }
  };

  instance.exports.i13_run();
  verify();

  // i13_run must be a fresh deterministic execution, not accumulated Wasm state.
  instance.exports.i13_run();
  verify();

  console.log(`WASM PARITY OK · ${expected.size} checked global(s) · repeat deterministic`);
}

main().catch(error => {
  console.error(error.stack || error);
  process.exit(1);
});
